# PlayerVaults by drsthock
# http://dev.bukkit.org/server-mods/playervaults

# Whether or not you want to check for updates.
# Will not download an update, that is your job :)
check-update: true

# Worlds that players can't access their vaults.
# playervaults.worlds.bypass will override this (default to op).
disabled-worlds:
  - YourAwesomeWorld
  - Toonville