name: PlayerVaults
main: com.drtshock.playervaults.Main
authors: [drtshock, gomeow, chester]
version: 2.1.0
website: http://dev.bukkit.org/server-mods/PlayerVaults
commands:
  pv:
    description: Open a vault with /vault <number>
    aliases: [vault, playervault, playervaults]
  pvdel:
    description: Delete a vault.