name: PlayerVaults
main: me.shock.playervaults.Main
authors: [drtshock, gomeow]
version: 2.0.0
website: www.dev.bukkit.org/server-mods/PlayerVaults
commands:
  pv:
    description: Open a vault with /vault <number>
    aliases: [vault, playervault, playervaults]
  pvdel:
    description: Delete a vault.